export const SEARCH_MANGA = 'SEARCH_MANGA';
export const FETCH_MANGAS = 'FETCH_MANGAS';
export const TRENDING_MANGAS = 'TRENDING_MANGAS';
export const TOGGLE_BOOKMARKED = 'TOGGLE_BOOKMARKED';
export const TOGGLE_BOOKMARKED_ERR = 'TOGGLE_BOOKMARKED_ERR';
export const BOOKMARK_START = 'BOOKMARK_START';

export const ADD_TO_BOOKMARK = 'ADD_TO_BOOKMARK';
export const ADD_TO_BOOKMARK_ERR = 'ADD_TO_BOOKMARK_ERR';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const ADD_TO_QUEUE_ERR = 'ADD_TO_QUEUE_ERR';
export const ADD_TO_WATCHING = 'ADD_TO_WATCHING';
export const ADD_TO_WATCHING_ERR = 'ADD_TO_WATCHING_ERR';
export const ADD_TO_COMPLETED = 'ADD_TO_COMPLETED';
export const ADD_TO_COMPLETED_ERR = 'ADD_TO_COMPLETED_ERR';

export const REMOVE_MANGA_START = 'REMOVE_MANGA_START';
export const REMOVE_MANGA = 'REMOVE_MANGA';
export const REMOVE_MANGA_ERR = 'REMOVE_MANGA_ERR'


export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERR = 'SIGN_UP_ERR';

export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const CLEAN_UP = 'CLEAN_UP';

export const VERIFY_START = 'VERIFY_START';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';

export const RECOVERY_START = 'RECOVERY_START';
export const RECOVERY_SUCCESS = 'RECOVERY_SUCCESS';
export const RECOVERY_FAIL = 'RECOVERY_FAIL';

export const PROFILE_EDIT_START = 'PROFILE_EDIT_START';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAIL = 'PROFILE_EDIT_FAIL';

export const DELETE_START = 'DELETE_START';
export const DELETE_FAIL = 'DELETE_FAIL';

export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';